services:
  flask:
    build:
      context: .
      dockerfile: docker/Dockerfile
    platform: linux/amd64
    command: /srv/.env/bin/flask run --host 0.0.0.0 --port 1237
    ports:
      - 127.0.0.1:1237:1237
    volumes:
      - ./src:/srv/nostrtool/src
    environment:
      - FLASK_APP=src/app